[package]
name = "libtabun"
version = "0.3.0"
authors = ["TyanNN <tyannn@cocaine.ninja>"]

[dependencies]
hyper		= "0.8.1"
multipart	= {version = "0.7.0", features = ["client"]}
select		= "*"
regex		= "*"
cookie		= "0.2.5"
unescape        = "*"
