[package]
name = "libtabun"
version = "0.1.0"
authors = ["TyanNN <tyannn@cocaine.ninja>"]

[dependencies]
hyper		= "0.8"
multipart	= "0.7.0"
select		= "*"
regex		= "*"
cookie		= "*"
time		= "*"
mdo 		= "*"
