[package]
name = "libtabun"
version = "0.4.0"
authors = ["TyanNN <tyannn@cocaine.ninja>"]

[dependencies]
hyper          = "*"
url            = "*"
multipart      = "*"
select         = "*"
regex          = "*"
unescape       = "*"
